### ISSUE TITLE
VIP was not assigned

### ISSUE THREAD

**Issue by KrystianMarek** [KrystianMarek/talos-on-equinix-metal#3]
With control plane config:
```yaml
#!talos
version: v1alpha1
debug: false
persist: true
machine:
  type: controlplane
  token: REDACTED
  ca:
    crt: REDACTED
    key: REDACTED
  certSANs: []
  kubelet:
    image: ghcr.io/siderolabs/kubelet:v1.26.1
    defaultRuntimeSeccompProfileEnabled: true
    disableManifestsDirectory: true
    extraArgs:
      cloud-provider: external
      provider-id: '"equinixmetal://{{ `{{ v1.instance_id }}` }}" '
  network:
    interfaces:
      - interface: eth3
        vip:
          ip: REDACTED
          equinixMetal:
            apiToken: REDACTED
```
VIP was not assigned to the machine
![image](https://user-images.githubusercontent.com/15972035/226912800-0f2be1cb-a64f-4944-b353-33a4a7a1c282.png)
